- examples/tensor_tests/CMakeLists.txt
- examples/tensor_tests/test_tensor.f90
- fortran-pytorch-lib/ctorch.cpp
- fortran-pytorch-lib/ctorch.h
- fortran-pytorch-lib/ftorch.f90
As documented in #24.  Essentially by wrapping the PyTorch `torch::from_blob` functions (https://pytorch.org/cppdocs/api/namespace_torch.html#namespace-torch) that take `strides` as an argument we can permit users to implicitly transform their data.  E.g. from Fortran indexing to C, or vice-versa.
We will provide Fortran interfaces to suit ordinary and power users.
> Allow users to use strides in Tensor creation

- examples/1_ResNet18/README.md
closes #26 . When following the [README](https://github.com/Cambridge-ICCS/fortran-pytorch-lib/blob/main/examples/1_ResNet18/README.md) of the ResNet18 example I found some typos in the instructions for the compilation of the `resnet_infer` files.
> Fixing typos in the README of the ResNet18 example

- examples/1_ResNet18/resnet_infer_fortran.f90
Thank you for this nice resource! I tried the ResNet18 example and noticed that the in/out layouts are missing at the call to `torch_tensor_from_blob`. This is a quick fix for that.
> Fixed missing array layouts in ResNet18 example

- examples/1_ResNet18/resnet18.py
> Update deprecated pytorch arguments in ResNet example.

- README.md
- src/CMakeLists.txt
- src/ctorch.cpp
- src/ftorch.f90
Resolves #9 and #45
Initial changes to allow FTorch to run on GPUs.
As discussed in #9, changes for CMake may not be required, but may be useful.
Additional documentation to be added.
> Update for GPUs

- examples/2_ResNet18/resnet_infer_python.py
Increase the tolerance slightly to match the example Fortran tolerance, as the results may only match to around five significant figures.
(Without this change, it threw an assertion error for me when running `python resnet_infer_python.py`)
> Increase assertion tolerance for Python inference

- README.md
This is something I noticed when building on my M1 Mac. I've added a little guidance (a note) to suggest the most likely succesfull path to building for other such users.
> Update README.md to give some extra guidance to Mac OS X users 

- .github/workflows/fypp.yml
FYPP check isn't running in forks as set to:
```
on:
push:
```
which only works for pushes to the main repo.
This updates it to also run on pull requests from forks.
Means it will run twice on internal PRs but we can live with that.
> Make fypp CI run on PRs from forks.

- src/ctorch.cpp
- src/ctorch.h
Closes #89.
Drops commented out `torch_from_blob` C++ code and unused `torch_from_blob_f` header.
> Remove unused code

- examples/1_SimpleNet/pt2ts.py
- examples/2_ResNet18/pt2ts.py
- src/ftorch.f90
- src/ftorch.fypp
- utils/pt2ts.py
Closes #90.
This PR ensures the names PyTorch and TorchScript are used consistently throughout.
It also implements a nice-to-have reordering of the Fortran subroutines so that they are consistent with the C++ functions. (Happy to revert this if it is unwanted.)
> Consistency of package names

- FTorch.md
- README.md
- examples/1_SimpleNet/simplenet_infer_fortran.f90
- examples/2_ResNet18/resnet_infer_fortran.f90
- examples/3_MultiGPU/simplenet_infer_fortran.f90
- pages/examples.md
- pages/gpu.md
- pages/troubleshooting.md
Should close #109 
Following the discussion in #108 naming the array of input tensors `inputs` rather than `input` in any examples should increase clarity to new users.
I also added a short FAQ item on the subject.
> Rename input to inputs

- pages/troubleshooting.md
- src/ctorch.cpp
- src/ctorch.h
- src/ftorch.f90
- src/ftorch.fypp
This is an updated version of #78 rebased onto main after the GPU changes by @jwallwork23
@ElliottKasoar's comment on the original PR:
Resolves #73
Adds flags in all(?) functions that operate on tensors (tensor creation, model loading, forward) to optionally disable autograd, which should improve performance for inference.
Also adds a similar flag to set evaluation mode for the loaded model.
- Evaluation mode
- Contrary to my initial comments in #73, from testing evaluation mode does appear to be preserved, both between saving and loading TorchScript, and when applied to the loaded model.
- In most cases evaluation mode is therefore likely to already be set, but I think it's useful to have the option to change it, particularly if FTorch may be extended to facilitate training (#22).
- …
>  Add options for eval and gradient required #78 - rebase

- README.md
- pages/developer.md
- pages/index.md
This will close #106 
Adds guidance for developers:
> Add developer guide page

- README.md
- examples/1_SimpleNet/simplenet_infer_fortran.f90
- examples/2_ResNet18/resnet_infer_fortran.f90
- examples/3_MultiGPU/simplenet_infer_fortran.f90
- examples/4_MultiIO/multiionet_infer_fortran.f90
- pages/examples.md
- pages/gpu.md
- pages/troubleshooting.md
- src/ftorch.f90
- src/ftorch.fypp
Change the API to make assignment of data to a `torch_tensor` a subroutine.
This is in anticipation of the AutoGrad wotk led by @jwallwork23 in #139 
This work may take a while to complete, but we need to stablise the API in advance of the summer school and as we move towards a first release and JOSS.
This makes the changes to the API that are required for this work without changing anything underneath.
> Adjust the API in anticipation of future overloading

- pages/troubleshooting.md
Whilst working through helping a Windows user in #124 I found that the advice we provide could be clearer:
- Clarify that you need the C++ tools as part of the VS install 
- Link to the Base and HPC toolkits separately - currently we name both, but only link to the base
- Remove hardcoded filepath to be more generic
> Update Windows help

- examples/2_ResNet18/resnet_infer_fortran.f90
- src/ftorch.f90
- src/ftorch.fypp
Closes #149.
Needed to switch `requires_grad_opt` -> `requires_grad` and use `requires_grad_value` to handle defaults (as with `device_index`).
Tested in my autograd example.
> Fix `requires_grad` optional argument

- examples/1_SimpleNet/simplenet_infer_fortran.f90
- examples/2_ResNet18/resnet_infer_fortran.f90
- examples/3_MultiGPU/simplenet_infer_fortran.f90
- examples/4_MultiIO/multiionet_infer_fortran.f90
- pages/examples.md
- src/ftorch.f90
- src/ftorch.fypp
This PR adds a subroutine (`torch_tensor_array_delete`) to delete arrays of tensors. This eliminate the need to manually loop over all elements of the array calling `torch_tensor_delete`, see e.g.,
https://github.com/Cambridge-ICCS/FTorch/blob/490272ef5662936be26697d496b14f6a281214fa/examples/4_MultiIO/multiionet_infer_fortran.f90#L57-L60
Which now becomes,
https://github.com/Cambridge-ICCS/FTorch/blob/e24c38024e0ec8b03ecd0f8a3e6c269e42ac2a0c/examples/4_MultiIO/multiionet_infer_fortran.f90#L57-L58
> add subroutine to delete arrays of tensors

- .github/workflows/test_suite.yml
- README.md
- pages/cmake.md
- src/CMakeLists.txt
Aims to resolve #130.
From [tests on my fork](https://github.com/ElliottKasoar/FTorch/actions/runs/9688663217), it looks like there are a number of incompatibilities with the 95 and 2003s standards.
Some may be relatively simple to adjust for, particularly for the 2003 standard. For example, we use `iso_fortran_env` types that were [not added until 2008](https://fortranwiki.org/fortran/show/iso_fortran_env), and in some cases variables have `no IMPLICIT type`.
The exact difference is obscured by fypp, but it appears there are significantly more issues for the 95 standard.
Given that I'm not aware of anyone encountering compatibility issues, stating support for 2008+ (e.g. similar to [DL POLY](https://ccp5.gitlab.io/dlpoly-setup/setup.html#requirements)) is perhaps the best first step, and …
> Add tests for different Fortran standards

- examples/1_SimpleNet/requirements.txt
Very minor fix- missing `numpy` in requirements for this example, which is needed (internally by `torch` on this code). Otherwise you get messages like:
```
UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
```
popping up.
> Update requirements.txt for 1_SimpleNet

- examples/1_SimpleNet/README.md
- examples/2_ResNet18/README.md
- examples/3_MultiGPU/README.md
- examples/4_MultiIO/README.md
- examples/5_Autograd/README.md
A note to remind how to set the compiler in the examples if you built FTorch using a different compiler to that found automatically by CMake (this just bit me, bizarrely only after upgrading mac OS).
> Add comment to readme.md for SimpleNet about setting compiler

- examples/1_SimpleNet/CMakeLists.txt
- examples/2_ResNet18/CMakeLists.txt
- examples/3_MultiGPU/CMakeLists.txt
- examples/4_MultiIO/CMakeLists.txt
- examples/5_Looping/CMakeLists.txt
- examples/6_Autograd/CMakeLists.txt
- examples/n_c_and_cpp/CMakeLists.txt
- src/CMakeLists.txt
As discussed in a meeting users currently get a warning that CMake < 3.5 will be deprecated when building our code.
Since the minimum version that ships with many distros is above this (e.g. 3.26 on RHEL8) we can probably safely bump this to suppress the warning without issue.
Note that >3.5 may not be the minimum required version in actuality - we have not done an exhaustive test - but it was agreed that we should proceed this way until we receive an issue stating that it does not work on a particular version.
> Bump the minimum required CMake in all CMakeLists to 3.5

- src/ftorch.f90
- src/ftorch.fypp
> feat: use get_shape in to_array subroutines

- examples/6_Autograd/CMakeLists.txt
- examples/6_Autograd/autograd.f90
- src/ctorch.cpp
- src/ctorch.h
- src/ftorch.f90
- src/ftorch.fypp
this fixes an issue seen in PRs #173  and #166 where the test fails with error:
```
[ERROR]: Array allocated with wrong shape
```
Whilst it looks like I have fixed the problem by simply removing the lines... I can assure the reviewer that I didn't do that deliberately :wink: 
I think I have an idea why it doesn't work, and why those lines need to be removed. It essentially stems from 2 points:
1. the `data_out` pointer is declared as `intent(out)`
https://github.com/Cambridge-ICCS/FTorch/blob/e0d82698cc2543b1281f4606007fcc29d7c5c85b/src/ftorch.f90#L2415 
This means that the following lines don't have much meaning
https://github.com/Cambridge-ICCS/FTorch/blob/e0d82698cc2543b1281f4606007fcc29d7c5c85b/src/ftorch.f90#L2426-L2442
2.  Secondly, `sizes` is marked optional …
> change to_array routines to fix pointer issues

- src/ftorch.f90
- src/ftorch.fypp
Closes #172 
We have had a request for 5D tensor support.
This is from the ConvLSTM: https://paperswithcode.com/method/convlstm which is a type of NN used to analyse gridded data.
Given our initial application (climate sciences) it would make sense to support this as standard.
I have extended the ranks argument in the fypp code to now support 5-D (rank 5) tensors.
One point to discuss is whether we want to support slightly higher in anticipation of other applications (Rank 6 or perhaps 7) bearing in mind that doing so adds quite a lot of code/functions in the f90 file.
We should also perhaps add documentation noting the limit in Rank, and perhaps describing how to extend it for specific cases.
> Extend FTorch to cover 5-dimensional tensors.

- examples/1_SimpleNet/simplenet_infer_fortran.f90
- examples/2_ResNet18/resnet_infer_fortran.f90
- examples/4_MultiIO/multiionet_infer_fortran.f90
- examples/6_Autograd/autograd.f90
- src/ftorch_test_utils.f90
- src/ftorch_test_utils.fypp
In doing so, we avoid using variables of `real` type without a particular kind in the test utils.
> Extend `assert` subroutines to account for different `real` types

- .github/workflows/test_suite_ubuntu.yml
- .github/workflows/test_suite_windows.yml
- examples/1_SimpleNet/CMakeLists.txt
- examples/1_SimpleNet/pt2ts.py
- examples/1_SimpleNet/simplenet.py
- examples/1_SimpleNet/simplenet_infer_python.py
- examples/2_ResNet18/CMakeLists.txt
- examples/2_ResNet18/pt2ts.py
- examples/2_ResNet18/resnet18.py
- examples/4_MultiIO/CMakeLists.txt
- examples/4_MultiIO/multiionet.py
- examples/4_MultiIO/multiionet_infer_python.py
- examples/4_MultiIO/pt2ts.py
- examples/5_Looping/simplenet.py
- examples/6_Autograd/CMakeLists.txt
- examples/6_Autograd/autograd.py
- run_integration_tests.bat
- src/CMakeLists.txt
- src/test/README.md
this makes the integration tests more portable.
> test: make integration tests cross-platform

- .clang-format
- .github/workflows/fypp_checks.yml
- examples/n_c_and_cpp/CMakeLists.txt
- src/CMakeLists.txt
- src/ctorch.cpp
- src/ctorch.h
- src/ftorch.F90
- src/ftorch.fypp
closes #183 
This issue also affected windows and is also fixed by this PR.
Tldr; `FTorch` expects a `long int*` whilst the `libtorch` binary seems to be returning a `long long int*`.
Example output below.
```
[ 25%] Building CXX object CMakeFiles/ftorch.dir/ctorch.cpp.o
/Users/user/FTorch/src/ctorch.cpp: In function 'const long int* torch_tensor_get_sizes(torch_tensor_t)':
/Users/user/FTorch/src/ctorch.cpp:240:25: error: invalid conversion from 'const long long int*' to 'const long int*' [-fpermissive]
240 |   return t->sizes().data();
|          ~~~~~~~~~~~~~~~^~
|                         |
|                         const long long int*
```
The solution is to check which system we are running on (OS and architecture) and create a preprocess macro `-DUNIX` that we can use to switch …
> Long long fix

- .github/workflows/static_analysis.yml
- examples/1_SimpleNet/CMakeLists.txt
- examples/2_ResNet18/CMakeLists.txt
- examples/3_MultiGPU/CMakeLists.txt
- examples/4_MultiIO/CMakeLists.txt
- examples/5_Looping/CMakeLists.txt
- examples/6_Autograd/CMakeLists.txt
- examples/n_c_and_cpp/CMakeLists.txt
- pages/developer.md
- requirements.txt
- src/CMakeLists.txt
Today I discovered a CMake formatter: https://github.com/cheshirekow/cmake_format.
Seems like a good idea to add to the static analysis workflow. I did need to disable the formatter in a couple of places with particularly long lines.
(Most of the changes in this PR are auto-formatting changes.)
> Apply CMake formatting

- .github/workflows/test_suite_windows.yml
Previously I hard-coded the path to `libtorch` i.e., 
`-DCMAKE_PREFIX_PATH="C:\hostedtoolcache\windows\Python\3.12.7\x64\Lib\site-packages"`. 
This commit replaces the hard-code path using `pip show` to get the updated location and store it in a variable `%torch_path%` for later use i.e.,  `-DCMAKE_PREFIX_PATH=%torch_path%`
> wip: debugging windows CI

- .github/workflows/build_docs.yml
- .github/workflows/fypp_checks.yml
- .github/workflows/static_analysis.yml
- .github/workflows/test_suite_ubuntu.yml
- .github/workflows/test_suite_windows.yml
- pages/developer.md
- requirements.txt
- run_integration_tests.sh
More linting!
Adds linting for shell and GitHub Actions workflows:
* https://github.com/koalaman/shellcheck
* https://woodruffw.github.io/zizmor
Also fixes an oversight in the CMake linting setup.
> Linting for shell and GitHub Actions

- examples/2_ResNet18/resnet_infer_fortran.f90
- examples/6_Autograd/autograd.f90
- src/ftorch.F90
- src/ftorch.fypp
- src/ftorch_test_utils.f90
- src/ftorch_test_utils.fypp
Building in debug mode with gfortran 11.4.0 on Ubuntu 22.04, I came across several warnings, most of which are fixed in this PR. They are mostly minor but the ones to do with overloaded operators are an oversight of mine from #139.
> Lean on compiler

- src/ftorch.F90
- src/ftorch.fypp
- src/test/unit/test_constructors.pf
This PR merges into #76.
I hit a weird bug because all tests passed in debug mode but the new unit test for `torch_tensor_from_array` failed for me locally in release mode, with the following traceback:
```
test 1
Start 1: test_constructors
1: Test command: /home/joe/software/FTorch/src/build/test/unit/test_constructors "--verbose"
1: Test timeout computed to be: 10000000
1:  
1: 
1:  Start: <test_constructors_suite.test_torch_tensor_empty>
1: .   end: <test_constructors_suite.test_torch_tensor_empty>
1:  
1: 
1:  Start: <test_constructors_suite.test_torch_tensor_zeros>
1: .PASSED :: [test_torch_tensor_zeros] relative tolerance =  0.1000E-04
1:    end: <test_constructors_suite.test_torch_tensor_zeros>
1:  
1: 
1:  Start: <test_constructors_suite.test_torch_tensor_ones>
1: .PASSED :: …
```
> Call from_blob inside from_array

- examples/1_SimpleNet/CMakeLists.txt
- examples/2_ResNet18/CMakeLists.txt
- examples/3_MultiGPU/CMakeLists.txt
- examples/4_MultiIO/CMakeLists.txt
- examples/5_Looping/CMakeLists.txt
- examples/6_Autograd/CMakeLists.txt
- examples/n_c_and_cpp/CMakeLists.txt
- src/CMakeLists.txt
- src/test/unit/CMakeLists.txt
This should close #226 by setting an upper bound on the minimum required version to the most recent version of CMake (`3.31`).
See issue #226 and https://cliutils.gitlab.io/modern-cmake/chapters/basics.html#minimum-version for more explanation on why this is advised.
> Set upper CMake minimum version in CMakeLists across codebase.

- src/ftorch.F90
- src/ftorch.fypp
To follow #76.
This PR reorganises the main FTorch module to group things more logically:
1. Datatypes
2. Interfaces for core FTorch functionality
3. Interfaces for operator overloading of tensors
4. Procedures for constructing tensors
5. Procedures for interrogating tensors
6. Procedures for deallocating tensors
7. Overloaded operators for tensors
8. Torch model API
This PR also drops unnecessary imports and makes it so that the `device_index` argument can be passed as a Fortran `integer` rather than a `c_int`.
> Reorganise main mod

- src/ctorch.cpp
- src/ctorch.h
- src/ftorch.F90
- src/ftorch.fypp
- src/test/unit/CMakeLists.txt
- src/test/unit/test_tensor_operator_overloads.pf
Closes #221.
Closes #224.
This PR implements unit tests for the overloaded operators acting on tensors using funit.
While implementing these tests, I discovered that pre/post multiplication by scalar, post-division by scalar, and scalar exponent don't work if the scalar is non-integer. This was an oversight by me, which is fixed in this PR. It turns out you can multiply/divide any tensor by a [1] tensor and torch treats it as a scalar, so that's what I do here.
In the case of exponentiation, it doesn't seem to be valid to have a tensor exponent. I revised the implementation to use a `torch_scalar_t` type and restricted attention to the integer case for now.
> Unit tests for operator overloading; fix scalar bug

- README.md
- examples/1_SimpleNet/CMakeLists.txt
- examples/2_ResNet18/CMakeLists.txt
- examples/3_MultiGPU/CMakeLists.txt
- examples/4_MultiIO/CMakeLists.txt
- examples/5_Looping/CMakeLists.txt
- examples/6_Autograd/CMakeLists.txt
- src/CMakeLists.txt
- src/test/unit/CMakeLists.txt
This PR:
* Gives some information on additional build dependencies in the README. In particular that `torchvision` should be installed at the same time as `torch`.
* Drop `FATAL_ERROR` from CMake versioning, which is ignored.
> Minor build tweaks

- src/ctorch.cpp
- src/ctorch.h
Follows #32.
Applies similar section headings in the C header and C++ source as were introduced in the Fortran source. Involves some reordering of appearance so these line up.
> Reorganise C/C++ as in Fortran

- README.md
Fixes the link to the developer docs which was broken. Points to the build static HTML in this fix.
> Fix broken URL in README

- src/ftorch.F90
- src/ftorch.fypp
While working on #236, I hit an overflow error in the 3D `torch_tensor_from_array` unit test. Digging into it, I noticed that the `strides` array in `torch_tensor_from_blob` is not initialised to zero!
I also switched `tensor_shape` and `layout` to be assumed shape as I don't think assumed size is necessary.
> Ensure strides array initialised to zero

- examples/6_Autograd/autograd.f90
- examples/README.md
- src/test/unit/test_constructors.pf
- src/test/unit/test_tensor_operator_overloads.pf
Towards #211.
Follows #225.
This PR cuts down the amount of testing done in the autograd example. In particular, it moves the checks that input arrays aren't modified into the unit tests.
The PR also adds a missing summary for the autograd example in `examples/README.md`.
> Move input array checks out of autograd example

- src/ctorch.cpp
- src/ctorch.h
- src/ftorch.F90
- src/ftorch.fypp
- src/test/unit/test_tensor_operator_overloads.pf
Closes #246.
Implements and overload for the unary `-` operator: `torch_tensor_minus`, plus unit test.
> Implement `torch_tensor_minus` for taking negative of a tensor

- run_test_suite.sh
Should resolve #259
Moves `X_ONLY` to `RUN_X` and now checks:
```sh
if [ "${RUN_X}" = true ]; then
cd "${BUILD_DIR}/test/x"
ctest "${CTEST_ARGS}"
cd -
fi 
```
> Avoid double negatives in the run tests shell script to make things clearer

- examples/2_ResNet18/resnet_infer_fortran.f90
A mismatch in character array lengths was causing the wrong resnet category to be printed in the Fortran.
At some point lengths in the main routine were updated to 128, but not in the subroutine required to read categories leading to the arrays becoming garbled during the passing.
Also updates the filename strings to 128 for consistency, rather than seemingly arbitrary lengths.
> Bugfix: mismatch in Fortran array character array lengths in example 2

- src/test/unit/test_tensor_interrogation_cuda.pf
Looks like I failed to re-test later changes in #222.
Building with CUDA support I got
```
/home/joewa/software/FTorch/src/build/test/unit/test_tensor_interrogation_cuda.F90:64:19:
64 |     if (expected /= torch_tensor_get_device_index(tensor)) then
|                   1
Error: Function ‘torch_tensor_get_device_index’ at (1) has no IMPLICIT type
/home/joewa/software/FTorch/src/build/test/unit/test_tensor_interrogation_cuda.F90:77:8:
77 |    use test_tensor_interrogation_cuda
|        1
Fatal Error: Cannot open module file ‘test_tensor_interrogation_cuda.mod’ for reading at (1): No such file or directory
compilation terminated.
```
which is fixed here.
> Use `get_device_index` method in test

- src/ctorch.cpp
- src/ctorch.h
- src/ftorch.F90
- src/ftorch.fypp
- src/test/unit/test_tensor_interrogation.pf
- src/test/unit/test_tensor_interrogation_cuda.pf
Closes #248.
This PR adds functions for getting the data type and device type of a tensor, including unit tests. It also improves the consistency of the existing functions so that they are called `torch_tensor_get_X` but are mapped to methods of the `torch_tensor` class as just `get_X`. This makes it clearer what we are getting the rank/shape of when we call as functions, and reduces unnecessary verbosity when calling as methods.
Using the new utility for getting the device type, the operator overloads involving scalars are corrected so that CPU isn't assumed.
> Add `get_dtype` and `get_device_type` methods for `torch_tensor`

- pages/testing.md
- run_test_suite.sh
Closes #265 
Enforces use of a venv through setting `PIP_REQUIRE_VIRTUALENV=true` in the unix tests script.
Running without a virtual environment will give:
```console
./run_test_suite.sh --verbose --integration-only
ERROR: Could not find an activated virtualenv (required).
Error: Process completed with exit code 3.
```
> Enforce the use of a virtual environment in the integration testing script.

- README.md
- conda/README.md
- conda/environment_cpu.yaml
- conda/environment_cuda.yaml
- pages/cmake.md
This should hopefully address some of  #214 
Queries:
- What is best practice, should we be pinning versions to any extent? Currently I just name the packages
- Should we add a workflow to check anything? Seems like a lot more effort to do properly (without pip) and I do say in the docs this is not our preferred or maintained approach...
> Add conda environment files and instructions

- examples/3_MultiGPU/CMakeLists.txt
- examples/3_MultiGPU/README.md
- examples/3_MultiGPU/multigpu_infer_fortran.f90
- examples/3_MultiGPU/multigpu_infer_python.py
- examples/3_MultiGPU/pt2ts.py
- examples/3_MultiGPU/requirements.txt
- examples/3_MultiGPU/simplenet.py
Closes #253.
I decided to close #258 and split it into two separate PRs. Here's the first one that removes MPI from the multi-GPU example. (The second one will introduce a CPU-only example that uses MPI.)
Note that I decided to switch the names of the `multigpu.py` module / `MultiGPU` class back to `simplenet.py` / `SimpleNet` in this example. This is because the class is a direct copy. (Unlike in `MultiIONet`, where it's modified.)
> Remove MPI from multi-GPU example

- pages/cmake.md
- pages/examples.md
- pages/hpc.md
Should close #277 
Adds guidance/tips for building on a HPC system.
Namely:
- build and install considerations
- Path settings
- Environment and module settings
> Add HPC docs page.

- README.md
- conda/README.md
- conda/environment_mac.yaml
Can successfully build FTorch and utilise the MPS backend on Apple Silicon.
This provides an alternative for users on mac, and also acts as a workaround whilst we wait for https://github.com/pytorch/pytorch/issues/143571 to be resolved.
> Add instructions for a conda environment on mac

- FTorch.md
- pages/developer.md
Definition of macros is required for generating documentation. Currently docs do not build properly as Ford cannot parse ftorch.F90. Also adds a note to the developer docs to remind people this needs keeping in sync.
Note - keep an eye on this in future, if Ford cannot parse a source file it generates a "warning" of the error rather than failing, so future PRs should include a cursory glance over what is generated.
> Patch docs to provide preprocessor macros to Ford

- test/unit/test_tensor_constructors.pf
- test/unit/test_tensor_interrogation.pf
- test/unit/test_tensor_interrogation_cuda.pf
- test/unit/test_tensor_operator_overloads.pf
This PR tidies up the unit tests considerably in light of #297.
There's no longer any need to call `torch_tensor_delete` (except for the test of it). I also spotted a way to refactor the error raising so that we don't need all the `clean_up` subroutines.
In some cases, we can use the inbuilt pFUnit assertions, which is nice.
> Cut down unit test code using destructor

- .github/workflows/JOSS_paper_pdf.yml
- paper/paper.bib
- paper/paper.md
This branch contains the FTorch submission for JOSS.
It will be kept up to date with the `main` branch (rebasing) throughout the review process.
Further additions to the paper will be made via commits to this `JOSS` branch.
Once review is complete we will merge it into main along with a citation.cff file and other post-review actions.
Review is at https://github.com/openjournals/joss-reviews/issues/7602#issuecomment-2552068472
> JOSS paper submission

- .github/workflows/static_analysis.yml
- fortitude.toml
- requirements.txt
- src/ftorch.F90
- src/ftorch.fypp
- src/ftorch_test_utils.f90
- src/ftorch_test_utils.fypp
- test/unit/test_tensor_constructors_destructors.pf
- test/unit/test_tensor_interrogation.pf
- test/unit/test_tensor_operator_overloads.pf
This PR updates to use the latest version of the Fortran fortitude linter which included a few API changes
Notably it adds:
- Ignoring of `C003` 'implicit none' missing 'external' as this is a f2013 feature and we want to support back to f2008.
- Adding an explicit `public` statement to the ftorch and test utils modules.
- This is correct for the test utils, but I think we should have a discussion about whether everything in the ftorch module should be public.
> Fortitude v0.7

- FTorch.md
- README.md
Adds the recent paper by Park and Chung as discussed.
Also updates the link and DOI for Heuer et al to the published version, removes CAM-ML as not actively using FTorch at the moment, and adds a brief description of what the papers show to the online docs.
> Add Park and Chung paper and add other details

- examples/6_Autograd/autograd.f90
- pages/autograd.md
- src/ctorch.cpp
- src/ctorch.h
- src/ftorch.F90
- src/ftorch.fypp
- test/unit/test_tensor_constructors_destructors.pf
- test/unit/test_tensor_interrogation.pf
Towards #158.
(Refined from #286.)
This PR hooks the `requires_grad` option up properly and provides a `torch_tensor_requires_grad` function (as well as a `torch_tensor%requires_grad` method) to query this. Unit tests are written and the option is also used in the autograd example.
> Hook up `requires_grad`

- .github/workflows/test_suite_ubuntu.yml
- examples/3_MultiGPU/multigpu_infer_fortran.f90
- examples/7_MPI/CMakeLists.txt
- examples/7_MPI/README.md
- examples/7_MPI/mpi_infer_fortran.f90
- examples/7_MPI/mpi_infer_python.py
- examples/7_MPI/pt2ts.py
- examples/7_MPI/requirements.txt
- examples/7_MPI/simplenet.py
- examples/CMakeLists.txt
- examples/README.md
- pages/examples.md
- pages/hpc.md
- run_test_suite.sh
Closes #257.
This PR creates a CPU-only example using MPI similarly to how we had the multi-GPU example set up before #268.
It's set up to run the net with different input on each MPI rank then gather the outputs to the root rank and check the outputs were correct. There's also a check that the number of MPI ranks is greater than 1 to help identify any config errors.
> MPI example

- src/ftorch.F90
- src/ftorch.fypp
As per the description, I spotted this on a stroll through ftorch.F90 so thought I'd fix.
Seems to have been a copy-paste error.
> Typo correction of is_training variable description in the ftorch API.

- CHANGELOG.md
- pages/changelog.md
- pages/developer.md
- pages/updates.md
Aims to address #312 
This PR adds a Changelog following https://keepachangelog.com/en/1.0.0/ and sets out guidance for how we should version the project in the future moving forward from 1.0.0
I do not intend this to be fully correct, but wanted to start the discussion so we can move towards something we agree on that is workable and get it in, as I feel it is important now.
> Versioning and Changelog

- test/unit/test_tensor_constructors_destructors.pf
Closes #318.
This test extends the fixtures in the existing unit tests for the constructors and destructors to cover the case where `torch_tensor_delete` is called and then a constructor is applied to the same tensor.
> Add tests for constructing after destructing

- CHANGELOG.md
I forgot to mention the changes that came with #319 in the newly added changelog.
Going forward, we should add changes to the changelog in the PR that introduces them, where possible.
> Mention test changes in changelog

- .github/workflows/static_analysis.yml
* Renames references to requirements.txt to requirements-dev.txt (needed after #331)
* Adds requirements-dev.txt to triggering changed paths
> Fix static analysis workflow (failing after #331)

- CHANGELOG.md
- pages/autograd.md
- src/ctorch.cpp
- src/ctorch.h
- src/ftorch.F90
- src/ftorch.fypp
- test/unit/test_tensor_autograd.pf
Closes #340.
> As mentioned in #320, we need to expose the `retain_graph` optional argument of the backpropagation operator in order to be able to run it multiple times.
Note that the branch used in this PR is based off the one from #341 so that one will need to be merged first.
> Expose `retain_graph` argument for `backward`

- CHANGELOG.md
- pages/autograd.md
- src/ctorch.cpp
- src/ctorch.h
- src/ftorch.F90
- src/ftorch.fypp
- test/unit/CMakeLists.txt
- test/unit/test_tensor_autograd.pf
Closes #336.
This PR adds a subroutine (and corresponding class method) for zeroing the gradients associated with the tensor.
The caveat that had been tripping me up until now is that you need to call `torch_tensor_get_gradient` after zeroing the gradients. It'd be nice if we could find a way round this, but I guess it's okay for now so long as it's documented.
> Implement zeroing of gradients

- CHANGELOG.md
- pages/tensor.md
- src/ctorch.cpp
- src/ctorch.h
- src/ftorch.F90
- src/ftorch.fypp
- test/unit/CMakeLists.txt
- test/unit/test_tensor_manipulation.pf
While working on #336, I wrapped the `Tensor.zero_` method and thought it might be useful.
To support this, I added a unit test module for tensor manipulation.
> Implement `torch_tensor_zero`

- .github/workflows/test_suite_ubuntu.yml
This resolves the failing CMake fPUnit workflows by forcing a compatible version at build time in the workflow.
I am about to open a PR to pFUnit to resolve it more generally at their level and will see if it fixes the issue here.
> Use fork of pFUnit with CMake version bumped to resolve failing install in workflows

- src/ftorch.F90
- src/ftorch.fypp
Apologies for not adding these when I added these procedures. I also added a few that were missing from other procedures.
> Variable definitions in docstrings for tensor API

- CHANGELOG.md
- examples/1_Tensor/tensor_manipulation.f90
- examples/2_SimpleNet/simplenet_infer_fortran.f90
- examples/3_ResNet/resnet_infer_fortran.f90
- examples/4_MultiIO/multiionet_infer_fortran.f90
- examples/6_MultiGPU/multigpu_infer_fortran.f90
- examples/7_MPI/mpi_infer_fortran.f90
- examples/8_Autograd/autograd.f90
- pages/tensor.md
- pages/transposing.md
- src/ftorch.F90
- src/ftorch.fypp
- test/unit/test_tensor_autograd.pf
- test/unit/test_tensor_constructors_destructors.pf
- test/unit/test_tensor_manipulation.pf
- test/unit/test_tensor_operator_overloads.pf
- test/unit/test_tensor_operator_overloads_autograd.pf
Closes #337.
It'd be convenient to default the tensor layout to `[1, 2, ..., n]`, as mentioned in #337. However, because this argument to `torch_tensor_from_array` comes before `device_type` (which is not optional), we can't simply make the `layout` argument optional because it would break the current API.
Thanks to the magic of `fypp`, this PR takes an alternative approach of providing more interfaces to `torch_tensor_from_array` such that it can be called without the `layout` argument, in which case it just gets the default value.
[As usual, the vast majority of lines added are due to fypp.]
> `torch_tensor_from_array` interface with default layout

- src/ctorch.cpp
- src/ftorch.F90
- src/ftorch.fypp
Closes #327.
As discussed in-person, it shouldn't be allowed to modify a tensor that has `requires_grad=true` because this is a tensor that's marked as something we differentiate with respect to. This PR raises an error if someone attempts to do so.
~~Unfortunately, I had to raise the error on the C++ side because it didn't work on the Fortran side in `torch_tensor_assign`. The reason is that the `output` tensor is actually the return value of a function, so we can't query its attributes. It seems to always be set to `.false.`. However, it is possible to do this when its pointer gets passed to C++.~~
Edit: Ignore me! Having set things back up on my fresh OS, I'd set up my editor autocmds incorrectly and was auto-generating `ftorch.f90` rather than `ftorch.F90`. The error is now raised on …
> Raise an error if user attempts to assign to tensor with `requires_grad=.true.`

- CHANGELOG.md
- src/ctorch.cpp
This PR intends to improve the handling of errors in C++ to make things a little more instructive for users when things go wrong, rather than just having a bare stacktrace.
Currently there is some handling within FTorch to check tensors are created.
This adds handling on the C++ side to try and tell users why something has failed.
It is unclear how to test for this with pFUnit. At the moment I write some code, break it accordingly, and check I see the error expected...
Implemented:
- These have not been made public or added to `ctorch.h` as designed to be used internally
- tensor is defined
- tensor has requires_grad
- gradient is defined for a tensor
Checking is not performed for getters (interrogation functions) or overloads (other than assign) as I felt probably unnecessary here.
This …
> Add error handling 

- src/ftorch.F90
- src/ftorch.fypp
I don't think we should be carrying over the `requires_grad` property with overloaded operations. This should only be used for tensors that we want to differentiate w.r.t.
> Do not carry over `requires_grad` with overloaded ops

- src/ftorch.F90
- src/ftorch.fypp
Updates to a consistent argument order and ensures wrapped subroutine arguments do not shadow outer scope.
Should close #361
> Tidying of wrapped functions in ftorch.F90

- src/ctorch.cpp
- src/ftorch.F90
- src/ftorch.fypp
- test/unit/test_tensor_autograd.pf
- test/unit/test_tensor_constructors_destructors.pf
- test/unit/test_tensor_interrogation.pf
- test/unit/test_tensor_operator_overloads.pf
- test/unit/test_tensor_operator_overloads_autograd.pf
Closes #370.
It turns out I was wrong in #364. Some simple Python experimentation shows that we *should* be carrying `requires_grad` over through expressions.
```
>>> a = torch.Tensor([1])
>>> a.requires_grad = True
>>> a
tensor([1.], requires_grad=True)
>>> b = torch.Tensor([2])
>>> c = a + b
>>> c
tensor([3.], grad_fn=<AddBackward0>)
>>> c.requires_grad
True
```
This PR reverts the changes from #364 and drops the related check that was causing issues.
Further, we should actually be overwriting with `requires_grad=False` when appropriate, too:
```
>>> import torch
>>> a = torch.Tensor([1])
>>> a.requires_grad=True
>>> a
tensor([1.], requires_grad=True)
>>> b = torch.Tensor([1])
>>> b
tensor([1.])
>>> a = b + b
>>> a
tensor([2.])
```
> `requires_grad` *should* be carried through expressions

- examples/1_Tensor/tensor_manipulation.f90
- pages/tensor.md
- pages/troubleshooting.md
Closes #305.
Brings much-needed clarity on the overloaded assignment operator.
This PR is somewhat of a companion of #373, in that I discovered some of this stuff while working on it.
> Docs on overloaded assignment operator

- src/ctorch.cpp
This would patch #365. 
As discussed in #365 this PR would fix the bug that sneaked in at 864b0eb causing any call to `torch_tensor_from_array` on a gpu device to throw
```
[ERROR]: The specified pointer resides on host memory and is not
registered with any CUDA device.
```
It rolls back to previous approach (6deab9a) where the device is not explicitly passed to the `options` but the tensor is rather moved `to` the target device.
> Fix bug in implementation of wrapper function `torch_from_blob` (#365)

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- README.md
- codespace/README.md
- codespace/build_FTorch.sh
This PR adds integration with GitHub Codespaces for running demonstrations and workshops.
Done via a devcontainer and Dockerfile
To launch go to this branch on the FTorch page, click "code" -> "Codespaces" -> "Create Codespace on codespace"
This will drop you into a codespace session within VSCode in browser.
From here we can build FTorch using:
```sh
mkdir build
cd build
python3 -m venv venv
source venv/bin/activate
pip install torch --index-url https://download.pytorch.org/whl/cpu
cmake .. \
-DCMAKE_BUILD_TYPE=Release \
-DCMAKE_PREFIX_PATH=/workspaces/FTorch/build/venv/lib/python3.10/site-packages/torch \
-DCMAKE_INSTALL_PREFIX=/workspaces/FTorch/bin
cmake --build . --target install
```
Note we need to specify the CPU wheel for pytorch, otherwise we get a bunch of CUDA infrastructure …
> Add Codespace for running FTorch Online

- CMakeLists.txt
- examples/2_SimpleNet/pt2ts.py
- examples/3_ResNet/pt2ts.py
- examples/4_MultiIO/pt2ts.py
- examples/5_Looping/pt2ts.py
- examples/6_MultiGPU/multigpu_infer_fortran.f90
- examples/6_MultiGPU/multigpu_infer_python.py
- examples/6_MultiGPU/pt2ts.py
- examples/7_MPI/pt2ts.py
- src/ctorch.cpp
- src/ctorch.h
- src/ftorch.F90
- src/ftorch.fypp
- utils/pt2ts.py
Merges into #385.
Some extras to add a `torch_kHIP` enum (aliased to `torch_kCUDA`) and to accept a `hip` device type option for the `pt2ts.py` scripts.
> Add `torch_kHIP` and `hip` device type for `pt2ts`

- FTorch.md
- pages/presentations.md
Closes #379.
This PR mentions the FTorch workshop repo on the main webpage. It also separates out the event listing into news vs training.
> Mention FTorch workshop repo and separate out events

- FTorch.md
- pages/presentations.md
Moves the event from upcoming events to the presentation archive. Reorders past trainings in reverse order, consistently with the past talks.
> Move AOPP tutorial to presentation archive

- FTorch.md
- pages/presentations.md
Also move summer school '25 into the events archive.
> Make info on citing FTorch more prominent

- .github/workflows/build_docs.yml
- FTorch.md
- pages/developer.md
Turns out by default FORD runs in a debug mode :upside_down_face:. 
So it prints a message to a console on some exceptions. 
Switching it off should make it fail. It is still draft since I want to test if the warning due to missing `graphviz` will also trip the build.
> Make FORD fail on warnings

- .github/workflows/test_suite_ubuntu_cuda.yml
- CMakeLists.txt
- examples/6_MultiGPU/CMakeLists.txt
The need for this was prompted by #410 since the runner used to do the GPU testing offers just 1 GPU.
**Note**: This would change the build behavior as building MultiGPU integration tests now explicitely requires setting `MULTI_GPU=ON`
> Add cmake optional variable `MULTI_GPU` to switch `ON`/`OFF` 

- examples/3_ResNet/resnet_infer_python.py
fix: prevent gradient calculation in inference mode
Add torch.no_grad() context manager to the model inference step
to avoid unnecessary computation and memory usage.
> fix a minor bug

- pages/developer.md
Should resolve #439 
Makes it explicit that we expect code to obey `cmake-lint` from `cmake-format`, but do not apply the formatter as it is overly opinionated making line-length a target rather than a goal, thereby reducing readability (in our opinion).
This should make it explicit in the docs following fair confusion in a community contribution PR.
This was originally discussed back in https://github.com/Cambridge-ICCS/FTorch/pull/204
> Add a note to developer pages to explicitly state use of cmake-lint but not the formatter.

- .github/workflows/JOSS_paper_pdf.yml
- .github/workflows/build_docs.yml
- .github/workflows/fypp_checks.yml
- .github/workflows/static_analysis.yml
- .github/workflows/test_suite_ubuntu.yml
- .github/workflows/test_suite_ubuntu_cuda.yml
- .github/workflows/test_suite_windows.yml
- requirements-dev.txt
It turns out there's a Zizmor GitHub Action that we could be using instead of the current manual approach: https://docs.zizmor.sh/integrations/.
With this action, we get Security info (see comment below), which I also address in this PR. Namely:
* Avoid giving anything write permissions that doesn't need it.
* Pin community actions to a specific hash.
Also includes some relabelling for consistency.
> Use Zizmor action
