Cambridge-ICCS/FTorch

README.md
c++ compiler options were incorrect
=> Update c++ compiler in README.md

examples/2_ResNet18/resnet_infer_fortran.f90
Tidying up Fortran code from the ResNet example, primarily to remove unused variables, as well as renaming `N` -> `tensor_length` to make it more meaningful and less likely to clash and `index` -> `idx`, to avoid overwriting a keyword.
=> Tidy example Fortran code

examples/2_ResNet18/resnet_infer_fortran.f90
Bug fix for #44 to correct a missed variable change.
=> Fix incorrect variable name

README.md, examples/1_SimpleNet/simplenet_infer_fortran.f90, examples/2_ResNet18/resnet_infer_fortran.f90, examples/tensor_tests/test_tensor.f90, src/ftorch.f90
See Cambridge-ICCS/FTorch-benchmarks#25
To do:
=> Ensure strings end with c_null_char

examples/1_SimpleNet/pt2ts.py, examples/2_ResNet18/pt2ts.py
Remove redundant lines that caused errors when uncommented running on GPU.
=> Patch on example utils files.

README.md
Add @ElliottKasoar and @TomMelt to the contributors list of the README.md
=> Update major contributors

examples/1_SimpleNet/pt2ts.py, examples/1_SimpleNet/simplenet.py, examples/2_ResNet18/pt2ts.py, utils/pt2ts.py
Resolves #92 
Applies black v24.3.0 to code.
=> Reformat python files with latest black

README.md
Closes #119 
Thanks for raising @christopheredsall
=> Fix broken link to slides on README.md

README.md, pages/updates.md
This PR adds a web docs page explaining the API changes and how to update following the breaking changes of #136 and #143 
This can then be sent to known users to help them update.
=> Add a web docs page explaining the API changes and how to update.

examples/4_MultiIO/README.md
Seems to render correctly now.
Note https://stackoverflow.com/questions/74177614/how-can-i-represent-a-matrix-in-github-markdown.
=> Fix LaTeX Markdown in example 4

examples/1_SimpleNet/simplenet_infer_fortran.f90, examples/2_ResNet18/resnet_infer_fortran.f90, examples/3_MultiGPU/simplenet_infer_fortran.f90, examples/4_MultiIO/multiionet_infer_fortran.f90, pages/examples.md, src/ftorch.f90, src/ftorch.fypp
This PR builds on #155 
This PR adds one centralized interface that is capable of deleting multiple torch objects:
https://github.com/Cambridge-ICCS/FTorch/blob/2aae63ab73b8166db7eca55574e580a199629619/src/ftorch.f90#L77-L82
=> add interface to delete all torch objects

README.md
Update README.md with citations for Mansfield and Sheshadri and Heuer et al papers using FTorch.
=> Update README.md with citations

FTorch.md, README.md
Fixes broken links to slides in README.
Will also propagate to online documentation.
=> Update README.md to fix broken links

README.md, pages/cmake.md
=> Update CMake references in docs to refer to version bump.

.clang-format, src/ctorch.cpp, src/ctorch.h
Sett Cpp column limit to 88 (as per ruff) for a nicer formatting based on observation.
=> Add clang-format config to set columnlimit for Cpp

requirements.txt, src/ftorch.F90, src/ftorch.fypp, src/ftorch_test_utils.f90, src/ftorch_test_utils.fypp
Also pins version in requirements.txt
Mostly whitespace updates, though I addded some alignment of FORD variable docs at the same time.
In future we should keep an eye out for major release updates and do periodic bumps.
This should be merged after #137
=> Bump to Fortitude 0.6.0

.github/workflows/fypp_checks.yml
Update fypp workflow to note that we preprocess ftorch into a .F90 file. Typo fix.
=> FYPP workflow typo fix

README.md
Small addition.
Opening as a PR because you are active on the target branch @jwallwork23.
=> Update example code in readme to specify device when loading model.

.github/workflows/test_suite_ubuntu.yml
=> Fix testing for Docker/Spack setup

pages/hpc.md
=> HPC Documentation enhancements as suggested by @TomMelt.

pages/cmake.md, pages/updates.md
As per title, fixes some broken links that crept into the docs.
=> Fix some broken links in the docs

.gitignore, pages/developer.md
As per title, fixes two minor issues.
=> Ignore `*.DS_Store` and fix `pre-commit` hook path in the docs

FTorch.md
As discussed the other day, I thought it'd be a good idea to add a News section to the website mentioning some recent/upcoming items.
=> Add news section to website

pages/autograd.md, test/unit/test_tensor_constructors_destructors.pf, test/unit/test_tensor_interrogation.pf, test/unit/test_tensor_interrogation_cuda.pf, test/unit/test_tensor_operator_overloads.pf, test/unit/test_tensor_operator_overloads_autograd.pf
This PR fixes some typos and cuts down various bits of duplicated code from the unit tests.
=> Spring cleaning

.github/workflows/test_suite_ubuntu.yml
Closes #352 
My contribution has been merged and a dew release 4.12 made.
=> Update to use version 4.12 of pFUnit following contributed fix.

FTorch.md, pages/archive.md
Closes #334.
Introduces a news archive.
Also provides slides for EuroAD talk.
Please feel free to suggest more past items!
=> News archive

FTorch.md
There are various upcoming talks and tutorials that we should advertise on the webpage.
=> Add upcoming events to webpage

FTorch.md, pages/presentations.md
Also mention location of Niccolo's recent presentation.
=> Convert Reading seminars to presentation

src/ftorch.F90, src/ftorch.fypp
A micro change that removes local variable that was indeed unused.
=> Fix unused-variable warning

pages/presentations.md
As per title, adds slides and talk to presentation page in the docs.
=> Add slides for the 2025 Oxford AOPP Seminar.

examples/2_SimpleNet/pt2ts.py, examples/3_ResNet/pt2ts.py, examples/4_MultiIO/pt2ts.py, examples/5_Looping/pt2ts.py, examples/6_MultiGPU/pt2ts.py, examples/7_MPI/pt2ts.py, utils/README.md, utils/pt2ts.py
Done throughout pt2ts files and associated READMEs in main utilities and exercises.
This matches a change made in the workshop https://github.com/Cambridge-ICCS/FTorch-workshop/pull/40
=> Update FPTLIB-TODO to bare TODO
